[build]
  publish = "out"
  command = "npm run build && npm run export"
[build.environment]
  NODE_VERSION = "18"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/favicon/*"
  [headers.values]
	cache-control = '''
	public,
  max-age=604800,
	immutable'''
